backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections: # A list of collections the CMS should be able to edit
  - name: 'projets' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Projets' # Used in the UI, ie.: "New Post"
    folder: 'content/projets' # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Image", name: "image", widget: "image", required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
- name: 'test_auto' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Test auto' # Used in the UI, ie.: "New Post"
    folder: 'content/test_auto' # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Image", name: "image", widget: "image", required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
